// brute Metal/MPS backend — driver layer.
//
// Mirrors the CPU + CUDA backend split:
//   * Kernels live in cbrute/metal/kernels/*.metal (one .metal file per
//     domain), compiled AOT by CMake into a single .metallib whose bytes are
//     embedded into the extension via brute_kernels_data.h (a generated
//     header).
//   * This .mm file is the host-side driver: shape validation, output
//     allocation, dispatch-helper plumbing, and PipelineCache.
//
// Why AOT? Apple's runtime MSL compiler is slow (~tens of ms for the legacy
// inlined string) and only validates kernels on first use. AOT shifts both
// costs to build time and lets us ship a single .so. We load the embedded
// bytes via [device newLibraryWithData:] at startup.
//
// Stream integration: when PyTorch's MPS stream is available we encode into
// its current command buffer. Before opening any compute encoder we MUST call
// `stream->endKernelCoalescing()` — otherwise a prior at:: op (e.g.
// at::bitwise_xor in a composite fallback) may still hold an encoder open on
// the same command buffer, triggering Metal's "A command encoder is already
// encoding to this command buffer" abort.

#ifdef HAVE_MPS
#import <Metal/Metal.h>
#include <torch/torch.h>

// PyTorch MPS stream integration (not in TORCH_STABLE_ONLY builds).
#if !defined(TORCH_STABLE_ONLY) && !defined(TORCH_TARGET_VERSION)
  #include <ATen/mps/MPSStream.h>
  #define BRUTE_MPS_STREAM 1
#endif

#include "ops_metal.h"
#include "brute_kernels_data.h"   // AUTO-generated by cmake/EmbedBinary.cmake
#include <algorithm>
#include <map>
#include <mutex>
#include <string>
#include <vector>

namespace cbrute { namespace mps {

//  Pipeline cache 
struct PipelineCache {
    std::mutex mtx;
    id<MTLDevice>      dev       = nil;
    id<MTLLibrary>     lib       = nil;
    id<MTLCommandQueue> own_queue = nil;   // used when PyTorch MPS stream is unavailable
    std::map<std::string, id<MTLComputePipelineState>> states;

    void ensure_lib() {
        if (lib) return;
        dev = MTLCreateSystemDefaultDevice();
        TORCH_CHECK(dev, "Metal: no default device");
        own_queue = [dev newCommandQueue];
        dispatch_data_t data = dispatch_data_create(
            kBruteKernelsMetallib, kBruteKernelsMetallib_len,
            nullptr, DISPATCH_DATA_DESTRUCTOR_DEFAULT);
        NSError* err = nil;
        lib = [dev newLibraryWithData:data error:&err];
        TORCH_CHECK(lib, "Metal library load failed: ",
                    err ? [[err localizedDescription] UTF8String] : "unknown");
    }

    id<MTLComputePipelineState> get(const std::string& name) {
        std::lock_guard<std::mutex> lock(mtx);
        auto it = states.find(name);
        if (it != states.end()) return it->second;
        ensure_lib();
        NSError* err = nil;
        id<MTLFunction> fn = [lib newFunctionWithName:
                              [NSString stringWithUTF8String:name.c_str()]];
        TORCH_CHECK(fn, "Metal kernel not found: ", name);
        id<MTLComputePipelineState> ps =
            [dev newComputePipelineStateWithFunction:fn error:&err];
        TORCH_CHECK(ps, "Metal pipeline error for ", name, ": ",
                    err ? [[err localizedDescription] UTF8String] : "unknown");
        states[name] = ps;
        return ps;
    }

    id<MTLCommandBuffer> cmd_buf() {
#if BRUTE_MPS_STREAM
        // Flush any pending at:: encoder on PyTorch's command buffer BEFORE
        // we open ours. Without this, computeCommandEncoderWithDispatchType:
        // aborts with "A command encoder is already encoding to this command
        // buffer" when the previous op left coalescing on.
        auto stream = at::mps::getCurrentMPSStream();
        stream->endKernelCoalescing();
        return (id<MTLCommandBuffer>)stream->commandBuffer();
#else
        std::lock_guard<std::mutex> lock(mtx);
        ensure_lib();
        return [own_queue commandBuffer];
#endif
    }

    void commit_if_standalone(id<MTLCommandBuffer> buf) {
#if !BRUTE_MPS_STREAM
        [buf commit];
        [buf waitUntilCompleted];
#endif
    }
};

static PipelineCache g_cache;

//  Helpers 

static inline id<MTLBuffer> mtl_buf(const at::Tensor& t) {
    return (__bridge id<MTLBuffer>)(t.storage().data());
}

static inline NSUInteger byte_offset(const at::Tensor& t) {
    return (NSUInteger)(t.storage_offset() * t.element_size());
}

static inline const char* pw_suffix(int64_t pw) {
    if (pw == 8)  return "_u8";
    if (pw == 32) return "_u32";
    return "_u64";
}

static inline const char* type_suffix(const at::Tensor& t) {
    switch (t.scalar_type()) {
        case at::kByte: case at::kBool: return "_u8";
        case at::kInt:                  return "_u32";
        default:                        return "_u64";
    }
}

//  Unified dispatcher 
// One entry point. The caller specifies the kernel name, buffer/offset pairs,
// inline int32 constants, the grid (in threads), and the threadgroup size.
// All MPS-stream coalescing handling is owned here.
static void dispatch_kernel(
        const std::string& name,
        const std::vector<std::pair<id<MTLBuffer>, NSUInteger>>& bufs,
        const std::vector<int32_t>& consts,
        MTLSize grid,
        MTLSize tg)
{
    auto ps  = g_cache.get(name);
    auto cmd = g_cache.cmd_buf();
    id<MTLComputeCommandEncoder> enc =
        [cmd computeCommandEncoderWithDispatchType:MTLDispatchTypeConcurrent];
    [enc setComputePipelineState:ps];
    NSUInteger idx = 0;
    for (const auto& bp : bufs) {
        [enc setBuffer:bp.first offset:bp.second atIndex:idx++];
    }
    for (int32_t v : consts) {
        [enc setBytes:&v length:sizeof(v) atIndex:idx++];
    }
    [enc dispatchThreads:grid threadsPerThreadgroup:tg];
    [enc endEncoding];
    g_cache.commit_if_standalone(cmd);
}

//  Op implementations 

static at::Tensor _pack_common(const std::string& kernel_name,
                               const at::Tensor& inp,
                               int64_t pw,
                               int element_bytes,
                               at::ScalarType out_dtype,
                               id<MTLBuffer> in_buf, NSUInteger in_off)
{
    const int64_t ld = inp.size(-1);
    auto out_shape = inp.sizes().vec();
    if (ld == 0) {
        out_shape.back() = 0;
        return at::zeros(out_shape, inp.options().dtype(out_dtype));
    }
    const int64_t pd_words  = (ld + pw - 1) / pw;
    const int64_t row_bytes = pd_words * (pw / 8);
    const int64_t batch     = inp.numel() / ld;
    out_shape.back() = pd_words;
    auto output = at::zeros(out_shape, inp.options().dtype(out_dtype));

    // 8 simdgroups per threadgroup, each handles one 32-bit chunk.
    const int chunks_per_row = (int)((ld + 31) / 32);
    const int tgs_x          = (chunks_per_row + 7) / 8;
    MTLSize grid = MTLSizeMake((NSUInteger)tgs_x * 256, (NSUInteger)batch, 1);
    MTLSize tg   = MTLSizeMake(256, 1, 1);

    dispatch_kernel(kernel_name,
        {{in_buf, in_off}, {mtl_buf(output), byte_offset(output)}},
        {(int32_t)ld, (int32_t)row_bytes},
        grid, tg);
    return output;
}

at::Tensor pack_bits(const at::Tensor& input, int64_t pw) {
    TORCH_CHECK(input.is_mps(), "brute::mps::pack_bits expects an MPS tensor");
    TORCH_CHECK(input.dim() >= 1, "pack_bits: input must have >= 1 dim");
    TORCH_CHECK(pw == 8 || pw == 32 || pw == 64, "pack_bits: pw must be 8/32/64");
    auto inp = input.contiguous().to(at::kFloat);
    at::ScalarType st = (pw == 8) ? at::kByte : (pw == 32) ? at::kInt : at::kLong;
    return _pack_common("pack_bits_chunked", inp, pw, 4, st,
                        mtl_buf(inp), byte_offset(inp));
}

at::Tensor pack_bool(const at::Tensor& input, int64_t pw) {
    TORCH_CHECK(input.is_mps(), "brute::mps::pack_bool expects an MPS tensor");
    TORCH_CHECK(input.dim() >= 1, "pack_bool: input must have >= 1 dim");
    TORCH_CHECK(pw == 8 || pw == 32 || pw == 64, "pack_bool: pw must be 8/32/64");
    TORCH_CHECK(input.scalar_type() == at::kBool,
                "pack_bool: input must be torch.bool");
    auto inp = input.contiguous();
    at::ScalarType st = (pw == 8) ? at::kByte : (pw == 32) ? at::kInt : at::kLong;
    return _pack_common("pack_bool_chunked", inp, pw, 1, st,
                        mtl_buf(inp), byte_offset(inp));
}

static at::Tensor _unpack_common(const std::string& kernel_name,
                                 const at::Tensor& packed,
                                 at::IntArrayRef logical_shape,
                                 int64_t pw,
                                 at::ScalarType out_dtype)
{
    const int64_t ll = logical_shape.back();
    if (ll == 0 || packed.numel() == 0) {
        return at::empty(logical_shape.vec(), packed.options().dtype(out_dtype));
    }
    auto p = packed.contiguous();
    const int64_t pl_words  = p.size(-1);
    const int64_t row_bytes = pl_words * (pw / 8);
    const int64_t batch     = p.numel() / pl_words;

    auto output = at::empty(logical_shape.vec(), p.options().dtype(out_dtype));
    const int chunks_per_row = (int)((ll + 31) / 32);
    const int tgs_x          = (chunks_per_row + 7) / 8;
    MTLSize grid = MTLSizeMake((NSUInteger)tgs_x * 256, (NSUInteger)batch, 1);
    MTLSize tg   = MTLSizeMake(256, 1, 1);

    dispatch_kernel(kernel_name,
        {{mtl_buf(p), byte_offset(p)}, {mtl_buf(output), byte_offset(output)}},
        {(int32_t)ll, (int32_t)row_bytes},
        grid, tg);
    return output;
}

at::Tensor unpack_bits(const at::Tensor& packed, at::IntArrayRef logical_shape, int64_t pw) {
    TORCH_CHECK(packed.is_mps());
    TORCH_CHECK(pw == 8 || pw == 32 || pw == 64);
    return _unpack_common("unpack_pm1_chunked", packed, logical_shape, pw, at::kFloat);
}

at::Tensor unpack_bool(const at::Tensor& packed, at::IntArrayRef logical_shape, int64_t pw) {
    TORCH_CHECK(packed.is_mps());
    TORCH_CHECK(pw == 8 || pw == 32 || pw == 64);
    return _unpack_common("unpack_bool_chunked", packed, logical_shape, pw, at::kBool);
}

//  Matmul 
// Three tiers of kernels, selected at runtime:
//
//  1. xnor_u32_tiled / xnor_u32_wide / xnor_u64_wide — fast paths.
//  2. Existing per-cell kernels (xnor_u8/u32/u64) — universal fallback.
//
// Tiled  (pw==32, M≥4, N≥8):
//   TG = (128, 2, 1) = 8 simdgroups, each handling one (m, n) within a
//   (TM=2, TN=4) output tile. A-tile and B-tile loaded once into threadgroup
//   memory per K-tile, amortising bandwidth across all 8 simdgroups.
//
// Wide u32 (pw==32, Kp%4==0, not tiled):
//   Same per-cell dispatch as the base kernel, but the shader processes 4
//   uint32 words per simdgroup-lane per K-iteration via uint4 loads.
//
// Wide u64 (pw==64, Kp%2==0):
//   Same per-cell dispatch; shader processes 2 ulong words per lane via ulong2.
at::Tensor xnor_popcount_matmul(const at::Tensor& A, const at::Tensor& B,
                                int64_t K, int64_t pw) {
    TORCH_CHECK(A.is_mps() && B.is_mps());
    TORCH_CHECK(A.dim() == 2 && B.dim() == 2);
    const int64_t M = A.size(0), N = B.size(0), Kp = A.size(1);
    TORCH_CHECK(Kp == B.size(1), "xnor_popcount_matmul: packed K mismatch");

    auto Ac = A.contiguous(), Bc = B.contiguous();
    auto C  = at::zeros({M, N}, A.options().dtype(at::kInt));
    const int32_t K_eff = (int32_t)(2LL * Kp * pw - K);

    //  Tier 1a: threadgroup-tiled u32 (large M × N)
    // TM=2, TN=4; TG = (TN*32, TM, 1) = (128, 2, 1).
    // Grid = (ceil(N/TN), ceil(M/TM), 1) in threadgroup coords, but we use
    // dispatchThreads which takes total threads so:
    //   grid_x = ceil(N/4) * 4 * 32,  grid_y = ceil(M/2) * 2.
    //
    // Within Tier 1a we pick the double-buffered variant (`xnor_u32_tiled_db`)
    // whenever Kp ≥ 2*KT — gives the pipeline at least one round of overlap.
    // KT=256 in the kernel; below that the bootstrap-only single-buffer kernel
    // is identical and slightly cheaper (no second tile alloc).
    constexpr int64_t TM = 2, TN = 4;
    constexpr int64_t KT = 256;
    if (pw == 32 && M >= TM * 2 && N >= TN * 2) {
        const int64_t grid_x = ((N + TN - 1) / TN) * TN * 32;
        const int64_t grid_y = ((M + TM - 1) / TM) * TM;
        MTLSize grid = MTLSizeMake((NSUInteger)grid_x, (NSUInteger)grid_y, 1);
        MTLSize tg   = MTLSizeMake((NSUInteger)(TN * 32), (NSUInteger)TM, 1);
        const char* kernel_name =
            (Kp >= 2 * KT) ? "xnor_u32_tiled_db" : "xnor_u32_tiled";
        dispatch_kernel(kernel_name,
            {{mtl_buf(Ac), byte_offset(Ac)},
             {mtl_buf(Bc), byte_offset(Bc)},
             {mtl_buf(C),  byte_offset(C)}},
            {(int32_t)N, (int32_t)Kp, K_eff, (int32_t)M},
            grid, tg);
        return C;
    }

    //  Tier 1b: wide-vector per-cell kernels 
    // xnor_u32_wide: Kp4 = Kp/4 wide words; xnor_u64_wide: Kp2 = Kp/2.
    // Grid/TG identical to the base per-cell kernels: (N*32, M) / (32, 1).
    if (pw == 32 && Kp % 4 == 0) {
        MTLSize grid = MTLSizeMake((NSUInteger)N * 32, (NSUInteger)M, 1);
        MTLSize tg   = MTLSizeMake(32, 1, 1);
        dispatch_kernel("xnor_u32_wide",
            {{mtl_buf(Ac), byte_offset(Ac)},
             {mtl_buf(Bc), byte_offset(Bc)},
             {mtl_buf(C),  byte_offset(C)}},
            {(int32_t)N, (int32_t)(Kp / 4), K_eff},
            grid, tg);
        return C;
    }
    if (pw == 64 && Kp % 2 == 0) {
        MTLSize grid = MTLSizeMake((NSUInteger)N * 32, (NSUInteger)M, 1);
        MTLSize tg   = MTLSizeMake(32, 1, 1);
        dispatch_kernel("xnor_u64_wide",
            {{mtl_buf(Ac), byte_offset(Ac)},
             {mtl_buf(Bc), byte_offset(Bc)},
             {mtl_buf(C),  byte_offset(C)}},
            {(int32_t)N, (int32_t)(Kp / 2), K_eff},
            grid, tg);
        return C;
    }

    //  Tier 2: base per-cell kernel (universal fallback) 
    MTLSize grid = MTLSizeMake((NSUInteger)N * 32, (NSUInteger)M, 1);
    MTLSize tg   = MTLSizeMake(32, 1, 1);
    dispatch_kernel(std::string("xnor") + pw_suffix(pw),
        {{mtl_buf(Ac), byte_offset(Ac)},
         {mtl_buf(Bc), byte_offset(Bc)},
         {mtl_buf(C),  byte_offset(C)}},
        {(int32_t)N, (int32_t)Kp, K_eff},
        grid, tg);
    return C;
}

//  Per-element popcount 
at::Tensor popcount(const at::Tensor& packed) {
    auto p = packed.contiguous();
    auto out = at::empty(p.sizes(), p.options().dtype(at::kInt));
    const int64_t n = p.numel();
    if (n == 0) return out;

    MTLSize grid = MTLSizeMake((NSUInteger)n, 1, 1);
    MTLSize tg   = MTLSizeMake(256, 1, 1);
    dispatch_kernel(std::string("popcnt") + type_suffix(p),
        {{mtl_buf(p), byte_offset(p)}, {mtl_buf(out), byte_offset(out)}},
        {},
        grid, tg);
    return out;
}

//  Total popcount / total hamming — two-pass reduction 
//
// Pass 1: each threadgroup of 256 threads grid-strides its slice and writes
//         one int32 partial. Number of threadgroups is sized to saturate the
//         GPU without producing a wasteful partials buffer.
// Pass 2: at::sum(partials, dtype=kLong) — handled natively by MPS.
// Tail   : if n_bytes % 8 != 0, a single-thread kernel reads the trailing
//         (< 8) bytes and atomic-adds the count to partials[0].
//
// We avoid 64-bit atomics (not universally available on Metal) by accumulating
// in int32 partials. Each partial is bounded by the per-threadgroup byte slice
// size, which is far under 2^31 for any practical input.

static int64_t pick_num_tgs(int64_t n_words) {
    // ~256 threadgroups saturates Apple Silicon (32-64 GPU cores * 8 SGs each
    // with some over-subscription). Clamp small problems down.
    const int64_t per_tg = 256;  // threads per TG; each thread takes one ulong
    int64_t tgs = (n_words + per_tg - 1) / per_tg;
    return std::clamp<int64_t>(tgs, 1, 1024);
}

static at::Tensor _total_popcount_buffer(id<MTLBuffer> in_buf, NSUInteger in_off,
                                         int64_t n_bytes,
                                         const at::TensorOptions& opts_on_mps) {
    auto opts_int32 = opts_on_mps.dtype(at::kInt);

    const int64_t n_words = n_bytes / 8;
    const int64_t tail    = n_bytes - n_words * 8;
    const int64_t n_tgs   = std::max<int64_t>(1, pick_num_tgs(n_words));
    auto partials = at::zeros({n_tgs}, opts_int32);

    if (n_words > 0) {
        MTLSize grid = MTLSizeMake((NSUInteger)n_tgs * 256, 1, 1);
        MTLSize tg   = MTLSizeMake(256, 1, 1);
        dispatch_kernel("packed_popcount_partial",
            {{in_buf, in_off}, {mtl_buf(partials), byte_offset(partials)}},
            {(int32_t)n_words},
            grid, tg);
    }
    if (tail > 0) {
        // Single-threadgroup tail accumulation. Pass the tail bytes via an
        // offset into the same input buffer.
        MTLSize grid = MTLSizeMake(1, 1, 1);
        MTLSize tg   = MTLSizeMake(1, 1, 1);
        dispatch_kernel("tail_popcount_u8",
            {{in_buf, in_off + (NSUInteger)(n_words * 8)},
             {mtl_buf(partials), byte_offset(partials)}},
            {(int32_t)tail},
            grid, tg);
    }
    // at::sum with dtype=kLong materializes the final scalar Tensor.
    return partials.sum(at::kLong);
}

at::Tensor packed_popcount(const at::Tensor& x) {
    auto p = x.contiguous();
    return _total_popcount_buffer(mtl_buf(p), byte_offset(p),
                                  (int64_t)p.nbytes(), p.options());
}

at::Tensor bit1_hamming_total(const at::Tensor& A, const at::Tensor& B) {
    TORCH_CHECK(A.sizes()       == B.sizes(),       "bit1_hamming_total: shape mismatch");
    TORCH_CHECK(A.scalar_type() == B.scalar_type(), "bit1_hamming_total: dtype mismatch");
    auto Ac = A.contiguous(), Bc = B.contiguous();

    const int64_t n_bytes = (int64_t)Ac.nbytes();
    const int64_t n_words = n_bytes / 8;
    const int64_t tail    = n_bytes - n_words * 8;
    const int64_t n_tgs   = std::max<int64_t>(1, pick_num_tgs(n_words));
    auto partials = at::zeros({n_tgs}, Ac.options().dtype(at::kInt));

    if (n_words > 0) {
        MTLSize grid = MTLSizeMake((NSUInteger)n_tgs * 256, 1, 1);
        MTLSize tg   = MTLSizeMake(256, 1, 1);
        dispatch_kernel("bit1_hamming_total_partial",
            {{mtl_buf(Ac), byte_offset(Ac)},
             {mtl_buf(Bc), byte_offset(Bc)},
             {mtl_buf(partials), byte_offset(partials)}},
            {(int32_t)n_words},
            grid, tg);
    }
    if (tail > 0) {
        MTLSize grid = MTLSizeMake(1, 1, 1);
        MTLSize tg   = MTLSizeMake(1, 1, 1);
        dispatch_kernel("tail_hamming_u8",
            {{mtl_buf(Ac), byte_offset(Ac) + (NSUInteger)(n_words * 8)},
             {mtl_buf(Bc), byte_offset(Bc) + (NSUInteger)(n_words * 8)},
             {mtl_buf(partials), byte_offset(partials)}},
            {(int32_t)tail},
            grid, tg);
    }
    return partials.sum(at::kLong);
}

//  Per-element hamming + bitwise (1-D, one thread per word) 
static at::Tensor binary_op(const std::string& prefix, const at::Tensor& A, const at::Tensor& B) {
    auto Ac = A.contiguous(), Bc = B.contiguous();
    auto C  = at::empty_like(Ac);
    MTLSize grid = MTLSizeMake((NSUInteger)Ac.numel(), 1, 1);
    MTLSize tg   = MTLSizeMake(256, 1, 1);
    dispatch_kernel(prefix + type_suffix(Ac),
        {{mtl_buf(Ac), byte_offset(Ac)},
         {mtl_buf(Bc), byte_offset(Bc)},
         {mtl_buf(C),  byte_offset(C)}},
        {},
        grid, tg);
    return C;
}

at::Tensor hamming_distance(const at::Tensor& A, const at::Tensor& B) { return binary_op("hamming", A, B); }

// Bitwise pass-throughs. PyTorch's MPSGraph elementwise ops are highly
// vectorised on integer dtypes and avoid the per-launch dispatch cost we
// paid in the previous custom-kernel path (one thread per word).
at::Tensor bitwise_and(const at::Tensor& A, const at::Tensor& B) { return at::bitwise_and(A, B); }
at::Tensor bitwise_or (const at::Tensor& A, const at::Tensor& B) { return at::bitwise_or (A, B); }
at::Tensor bitwise_xor(const at::Tensor& A, const at::Tensor& B) { return at::bitwise_xor(A, B); }
at::Tensor bitwise_not(const at::Tensor& A)                       { return at::bitwise_not(A);    }

at::Tensor& randomize_bits(at::Tensor& out) {
    out.random_();
    return out;
}

}} // cbrute::mps
#endif // HAVE_MPS
