// brute Metal/MPS backend — driver layer.
//
// All bit1 packed buffers are int64 (uint64 view, 64 bits per word). Kernels
// live in cbrute/metal/kernels/*.metal, compiled AOT by CMake into a single
// .metallib whose bytes are embedded into the extension via the generated
// brute_kernels_data.h. We load it at startup with [device newLibraryWithData:].
//
// Stream integration: when PyTorch's MPS stream is available we encode into
// its current command buffer. Before opening any compute encoder we MUST call
// `stream->endKernelCoalescing()` — otherwise a prior at:: op may still hold
// an encoder open on the same command buffer, triggering Metal's "A command
// encoder is already encoding to this command buffer" abort.

#ifdef HAVE_MPS
#import <Metal/Metal.h>
#include <torch/torch.h>

#if !defined(TORCH_STABLE_ONLY) && !defined(TORCH_TARGET_VERSION)
  #include <ATen/mps/MPSStream.h>
  #define BRUTE_MPS_STREAM 1
#endif

#include "ops_metal.h"
#include "brute_kernels_data.h"   // auto-generated by cmake/EmbedBinary.cmake
#include <algorithm>
#include <atomic>
#include <shared_mutex>
#include <string>
#include <unordered_map>
#include <vector>

namespace cbrute { namespace mps {

namespace {

constexpr int64_t PACK_WIDTH = 64;

//  Pipeline cache: two-tier.
//   * shared_mutex-guarded unordered_map handles arbitrary kernel names.
//   * Each call site holds a per-callsite atomic slot; hot dispatches bypass
//     the map after the first compile.
struct PipelineCache {
    std::shared_mutex mtx;
    id<MTLDevice>       dev       = nil;
    id<MTLLibrary>      lib       = nil;
    id<MTLCommandQueue> own_queue = nil;   // used when no MPS stream available
    std::unordered_map<std::string, id<MTLComputePipelineState>> states;

    void ensure_lib() {
        if (lib) return;
        dev = MTLCreateSystemDefaultDevice();
        TORCH_CHECK(dev, "Metal: no default device");
        own_queue = [dev newCommandQueue];
        dispatch_data_t data = dispatch_data_create(
            kBruteKernelsMetallib, kBruteKernelsMetallib_len,
            nullptr, DISPATCH_DATA_DESTRUCTOR_DEFAULT);
        NSError* err = nil;
        lib = [dev newLibraryWithData:data error:&err];
        TORCH_CHECK(lib, "Metal library load failed: ",
                    err ? [[err localizedDescription] UTF8String] : "unknown");
    }

    id<MTLComputePipelineState> get(const std::string& name) {
        {
            std::shared_lock<std::shared_mutex> rlock(mtx);
            auto it = states.find(name);
            if (it != states.end()) return it->second;
        }
        std::unique_lock<std::shared_mutex> wlock(mtx);
        auto it = states.find(name);
        if (it != states.end()) return it->second;
        ensure_lib();
        NSError* err = nil;
        id<MTLFunction> fn = [lib newFunctionWithName:
                              [NSString stringWithUTF8String:name.c_str()]];
        TORCH_CHECK(fn, "Metal kernel not found: ", name);
        id<MTLComputePipelineState> ps =
            [dev newComputePipelineStateWithFunction:fn error:&err];
        TORCH_CHECK(ps, "Metal pipeline error for ", name, ": ",
                    err ? [[err localizedDescription] UTF8String] : "unknown");
        states[name] = ps;
        return ps;
    }

    id<MTLCommandBuffer> cmd_buf() {
#if BRUTE_MPS_STREAM
        // Flush any pending at:: encoder on PyTorch's command buffer BEFORE
        // we open ours.
        auto stream = at::mps::getCurrentMPSStream();
        stream->endKernelCoalescing();
        return (id<MTLCommandBuffer>)stream->commandBuffer();
#else
        std::lock_guard<std::shared_mutex> lock(mtx);
        ensure_lib();
        return [own_queue commandBuffer];
#endif
    }

    void commit_if_standalone(id<MTLCommandBuffer> buf) {
#if !BRUTE_MPS_STREAM
        [buf commit];
        [buf waitUntilCompleted];
#endif
    }
};

static PipelineCache g_cache;

// Per-callsite cache: store the resolved pipeline state in a static atomic so
// subsequent dispatches at the same call site bypass the shared-mutex lookup
// entirely. Pipeline states are owned by g_cache for the program lifetime —
// safe to publish a raw pointer.
static inline id<MTLComputePipelineState> cached_pipeline(
        std::atomic<void*>& slot, const std::string& name) {
    void* p = slot.load(std::memory_order_acquire);
    if (p != nullptr) return (__bridge id<MTLComputePipelineState>)p;
    id<MTLComputePipelineState> ps = g_cache.get(name);
    slot.store((__bridge void*)ps, std::memory_order_release);
    return ps;
}
#define BRUTE_CACHED_PS(name) ([](){                                         \
        static std::atomic<void*> _ps_slot{nullptr};                         \
        return cached_pipeline(_ps_slot, (name));                            \
    }())

inline id<MTLBuffer> mtl_buf(const at::Tensor& t) {
    return (__bridge id<MTLBuffer>)(t.storage().data());
}
inline NSUInteger byte_offset(const at::Tensor& t) {
    return (NSUInteger)(t.storage_offset() * t.element_size());
}

// Map a torch tensor's scalar type → kernel suffix for the per-element
// `popcount` op (which legitimately supports any integer dtype).
inline const char* type_suffix(const at::Tensor& t) {
    switch (t.scalar_type()) {
        case at::kByte: case at::kBool: return "_u8";
        case at::kInt:                  return "_u32";
        default:                        return "_u64";
    }
}

//  Unified dispatcher
static void dispatch_kernel_ps(
        id<MTLComputePipelineState> ps,
        const std::vector<std::pair<id<MTLBuffer>, NSUInteger>>& bufs,
        const std::vector<int32_t>& consts,
        MTLSize grid, MTLSize tg)
{
    auto cmd = g_cache.cmd_buf();
    id<MTLComputeCommandEncoder> enc =
        [cmd computeCommandEncoderWithDispatchType:MTLDispatchTypeConcurrent];
    [enc setComputePipelineState:ps];
    NSUInteger idx = 0;
    for (const auto& bp : bufs) [enc setBuffer:bp.first offset:bp.second atIndex:idx++];
    for (int32_t v : consts)    [enc setBytes:&v length:sizeof(v)   atIndex:idx++];
    [enc dispatchThreads:grid threadsPerThreadgroup:tg];
    [enc endEncoding];
    g_cache.commit_if_standalone(cmd);
}

static void dispatch_kernel(
        const std::string& name,
        const std::vector<std::pair<id<MTLBuffer>, NSUInteger>>& bufs,
        const std::vector<int32_t>& consts,
        MTLSize grid, MTLSize tg)
{
    dispatch_kernel_ps(g_cache.get(name), bufs, consts, grid, tg);
}

}  // anon

//  pack_bool: bool → int64 packed buffer.
at::Tensor pack_bool(const at::Tensor& input) {
    TORCH_CHECK(input.is_mps(), "brute::mps::pack_bool expects an MPS tensor");
    TORCH_CHECK(input.dim() >= 1, "pack_bool: input must have >= 1 dim");
    TORCH_CHECK(input.scalar_type() == at::kBool,
                "pack_bool: input must be torch.bool");
    auto inp = input.contiguous();
    const int64_t ld = inp.size(-1);
    auto out_shape = inp.sizes().vec();
    if (ld == 0) {
        out_shape.back() = 0;
        return at::zeros(out_shape, inp.options().dtype(at::kLong));
    }
    const int64_t pd_words  = (ld + PACK_WIDTH - 1) / PACK_WIDTH;
    const int64_t row_bytes = pd_words * (PACK_WIDTH / 8);
    const int64_t batch     = inp.numel() / ld;
    out_shape.back() = pd_words;
    auto output = at::zeros(out_shape, inp.options().dtype(at::kLong));
    const int chunks_per_row = (int)((ld + 31) / 32);
    const int tgs_x          = (chunks_per_row + 7) / 8;
    MTLSize grid = MTLSizeMake((NSUInteger)tgs_x * 256, (NSUInteger)batch, 1);
    MTLSize tg   = MTLSizeMake(256, 1, 1);
    dispatch_kernel_ps(BRUTE_CACHED_PS("pack_bool_chunked"),
        {{mtl_buf(inp), byte_offset(inp)}, {mtl_buf(output), byte_offset(output)}},
        {(int32_t)ld, (int32_t)row_bytes}, grid, tg);
    return output;
}

namespace {
at::Tensor unpack_common(const std::string& kernel_name,
                         id<MTLComputePipelineState> ps,
                         const at::Tensor& packed, at::IntArrayRef logical_shape,
                         at::ScalarType out_dtype)
{
    const int64_t ll = logical_shape.back();
    if (ll == 0 || packed.numel() == 0)
        return at::empty(logical_shape.vec(), packed.options().dtype(out_dtype));
    auto p = packed.contiguous();
    const int64_t pl_words  = p.size(-1);
    const int64_t row_bytes = pl_words * (PACK_WIDTH / 8);
    const int64_t batch     = p.numel() / pl_words;
    auto output = at::empty(logical_shape.vec(), p.options().dtype(out_dtype));
    const int chunks_per_row = (int)((ll + 31) / 32);
    const int tgs_x          = (chunks_per_row + 7) / 8;
    MTLSize grid = MTLSizeMake((NSUInteger)tgs_x * 256, (NSUInteger)batch, 1);
    MTLSize tg   = MTLSizeMake(256, 1, 1);
    (void)kernel_name;  // kept for symmetry; the pipeline is already resolved.
    dispatch_kernel_ps(ps,
        {{mtl_buf(p), byte_offset(p)}, {mtl_buf(output), byte_offset(output)}},
        {(int32_t)ll, (int32_t)row_bytes}, grid, tg);
    return output;
}
}  // anon

at::Tensor unpack_bits(const at::Tensor& packed, at::IntArrayRef logical_shape) {
    TORCH_CHECK(packed.is_mps());
    return unpack_common("unpack_pm1_chunked",
                         BRUTE_CACHED_PS("unpack_pm1_chunked"),
                         packed, logical_shape, at::kFloat);
}

at::Tensor unpack_bool(const at::Tensor& packed, at::IntArrayRef logical_shape) {
    TORCH_CHECK(packed.is_mps());
    return unpack_common("unpack_bool_chunked",
                         BRUTE_CACHED_PS("unpack_bool_chunked"),
                         packed, logical_shape, at::kBool);
}

//  Matmul — two-tier dispatch:
//    * xnor_u64_wide  (ulong2 inner loop) when Kp % 2 == 0 — primary path
//    * xnor_u64       (scalar inner loop) for odd Kp
at::Tensor xnor_popcount_matmul(const at::Tensor& A, const at::Tensor& B, int64_t K) {
    TORCH_CHECK(A.is_mps() && B.is_mps());
    TORCH_CHECK(A.dim() == 2 && B.dim() == 2);
    const int64_t M = A.size(0), N = B.size(0), Kp = A.size(1);
    TORCH_CHECK(Kp == B.size(1), "xnor_popcount_matmul: packed K mismatch");

    auto Ac = A.contiguous(), Bc = B.contiguous();
    auto C  = at::empty({M, N}, A.options().dtype(at::kInt));
    const int32_t K_logical = (int32_t)K;

    MTLSize grid = MTLSizeMake((NSUInteger)N * 32, (NSUInteger)M, 1);
    MTLSize tg   = MTLSizeMake(32, 1, 1);

    if (Kp % 2 == 0) {
        dispatch_kernel_ps(BRUTE_CACHED_PS("xnor_u64_wide"),
            {{mtl_buf(Ac), byte_offset(Ac)},
             {mtl_buf(Bc), byte_offset(Bc)},
             {mtl_buf(C),  byte_offset(C)}},
            {(int32_t)N, (int32_t)(Kp / 2), K_logical},
            grid, tg);
    } else {
        dispatch_kernel_ps(BRUTE_CACHED_PS("xnor_u64"),
            {{mtl_buf(Ac), byte_offset(Ac)},
             {mtl_buf(Bc), byte_offset(Bc)},
             {mtl_buf(C),  byte_offset(C)}},
            {(int32_t)N, (int32_t)Kp, K_logical},
            grid, tg);
    }
    return C;
}

//  signed_bundle — int8-weight × bit1 → bit1; one thread per output word.
at::Tensor signed_bundle(const at::Tensor& W, const at::Tensor& V, int64_t D) {
    TORCH_CHECK(W.is_mps() && V.is_mps(), "signed_bundle: expects MPS tensors");
    TORCH_CHECK(W.dim() == 3 && V.dim() == 3,
                "signed_bundle: W (B,M,N), V packed (B,N,Dp)");
    TORCH_CHECK(W.scalar_type() == at::kChar, "signed_bundle: W must be int8");
    const int64_t B = W.size(0), M = W.size(1), N = W.size(2), Dp = V.size(2);
    TORCH_CHECK(V.size(0) == B && V.size(1) == N,
                "signed_bundle: W (B,M,N) / V (B,N,Dp) batch or N mismatch");
    auto Wc = W.contiguous(), Vc = V.contiguous();
    auto out = at::zeros({B, M, Dp}, V.options().dtype(at::kLong));
    const int64_t total = B * M * Dp;
    if (total == 0) return out;
    MTLSize grid = MTLSizeMake((NSUInteger)total, 1, 1);
    MTLSize tg   = MTLSizeMake(256, 1, 1);
    dispatch_kernel_ps(BRUTE_CACHED_PS("signed_bundle_kernel"),
        {{mtl_buf(Wc), byte_offset(Wc)},
         {mtl_buf(Vc), byte_offset(Vc)},
         {mtl_buf(out), byte_offset(out)}},
        {(int32_t)B, (int32_t)M, (int32_t)N, (int32_t)Dp, (int32_t)D},
        grid, tg);
    return out;
}

//  Per-element popcount — handles any integer dtype.
at::Tensor popcount(const at::Tensor& packed) {
    auto p = packed.contiguous();
    auto out = at::empty(p.sizes(), p.options().dtype(at::kInt));
    const int64_t n = p.numel();
    if (n == 0) return out;
    MTLSize grid = MTLSizeMake((NSUInteger)n, 1, 1);
    MTLSize tg   = MTLSizeMake(256, 1, 1);
    dispatch_kernel(std::string("popcnt") + type_suffix(p),
        {{mtl_buf(p), byte_offset(p)}, {mtl_buf(out), byte_offset(out)}},
        {}, grid, tg);
    return out;
}

namespace {
int64_t pick_num_tgs(int64_t n_words) {
    constexpr int64_t per_tg = 256;
    int64_t tgs = (n_words + per_tg - 1) / per_tg;
    return std::clamp<int64_t>(tgs, 1, 1024);
}
}  // anon

//  Total popcount — two-pass partial reduction → at::sum (kLong).
at::Tensor packed_popcount(const at::Tensor& x) {
    auto p = x.contiguous();
    auto opts_int32 = p.options().dtype(at::kInt);
    const int64_t n_bytes = (int64_t)p.nbytes();
    const int64_t n_words = n_bytes / 8;
    const int64_t tail    = n_bytes - n_words * 8;
    const int64_t n_tgs   = std::max<int64_t>(1, pick_num_tgs(n_words));
    auto partials = at::zeros({n_tgs}, opts_int32);

    if (n_words > 0) {
        MTLSize grid = MTLSizeMake((NSUInteger)n_tgs * 256, 1, 1);
        MTLSize tg   = MTLSizeMake(256, 1, 1);
        dispatch_kernel_ps(BRUTE_CACHED_PS("packed_popcount_partial"),
            {{mtl_buf(p), byte_offset(p)},
             {mtl_buf(partials), byte_offset(partials)}},
            {(int32_t)n_words}, grid, tg);
    }
    if (tail > 0) {
        MTLSize grid = MTLSizeMake(1, 1, 1);
        MTLSize tg   = MTLSizeMake(1, 1, 1);
        dispatch_kernel("tail_popcount_u8",
            {{mtl_buf(p), byte_offset(p) + (NSUInteger)(n_words * 8)},
             {mtl_buf(partials), byte_offset(partials)}},
            {(int32_t)tail}, grid, tg);
    }
    return partials.sum(at::kLong);
}

//  Per-element Hamming distance — composed from native at:: ops, both of which
//  have fast MPSGraph impls. Saves three Metal kernels (hamming_u8/u32/u64).
at::Tensor hamming_distance(const at::Tensor& A, const at::Tensor& B) {
    return popcount(at::bitwise_xor(A, B));
}

//  bit1_hamming_total — fused XOR + popcount + partial reduction.
at::Tensor bit1_hamming_total(const at::Tensor& A, const at::Tensor& B) {
    TORCH_CHECK(A.sizes()       == B.sizes(),       "bit1_hamming_total: shape mismatch");
    TORCH_CHECK(A.scalar_type() == B.scalar_type(), "bit1_hamming_total: dtype mismatch");
    auto Ac = A.contiguous(), Bc = B.contiguous();
    const int64_t n_bytes = (int64_t)Ac.nbytes();
    const int64_t n_words = n_bytes / 8;
    const int64_t tail    = n_bytes - n_words * 8;
    const int64_t n_tgs   = std::max<int64_t>(1, pick_num_tgs(n_words));
    auto partials = at::zeros({n_tgs}, Ac.options().dtype(at::kInt));

    if (n_words > 0) {
        MTLSize grid = MTLSizeMake((NSUInteger)n_tgs * 256, 1, 1);
        MTLSize tg   = MTLSizeMake(256, 1, 1);
        dispatch_kernel_ps(BRUTE_CACHED_PS("bit1_hamming_total_partial"),
            {{mtl_buf(Ac), byte_offset(Ac)},
             {mtl_buf(Bc), byte_offset(Bc)},
             {mtl_buf(partials), byte_offset(partials)}},
            {(int32_t)n_words}, grid, tg);
    }
    if (tail > 0) {
        MTLSize grid = MTLSizeMake(1, 1, 1);
        MTLSize tg   = MTLSizeMake(1, 1, 1);
        dispatch_kernel("tail_hamming_u8",
            {{mtl_buf(Ac), byte_offset(Ac) + (NSUInteger)(n_words * 8)},
             {mtl_buf(Bc), byte_offset(Bc) + (NSUInteger)(n_words * 8)},
             {mtl_buf(partials), byte_offset(partials)}},
            {(int32_t)tail}, grid, tg);
    }
    return partials.sum(at::kLong);
}

at::Tensor& randomize_bits(at::Tensor& out) { out.random_(); return out; }

}} // cbrute::mps
#endif // HAVE_MPS
