"""Binary Error Propagation (BEP) — fully binary MLP training.

Reference
---------
Colombo, Pittorino, Zambon, Baldassi, Roveri, Alippi.
"BEP: A Binary Error Propagation Algorithm for Binary Neural Networks
Training." ICLR 2026 (arXiv:2512.04189).

Algorithm at a glance
---------------------
* Each layer holds an integer "metaplasticity" weight ``H_l`` of shape
  ``(K_l, K_{l-1})`` in ``Z`` (clipped to ``[-2^{B-1}, 2^{B-1}-1]``, B=16).
  The *visible* binary weight is ``W_l = sign(H_l) in {±1}^{K_l x K_{l-1}}``,
  stored as ``brute.bit1`` for the XNOR/popcount fast path.

* Forward (Sec. 3.1)::
      a_0 = bin(x)                                # ±1
      z_l = W_l a_{l-1}                           # int32 dot in ±1 domain
      a_l = sign(z_l)                             # ±1
      y_hat = P a_L                               # logits via fixed BEF

* Update trigger (Eq. 1): the per-sample margin must be below ``r * K_L``.

* Backward (Eq. 7) — *fully binary* recursion::
      a*_L = rho^{c}                                       # correct class prototype
      a*_l = sign( W_{l+1}^T (g_{l+1} ⊙ a*_{l+1}) )        # for l < L
  where ``g_{l+1,i} = 1 iff |z_{l+1,i}| <= nu * K_l``.

* Weight update (Eq. 8/9) — winner-takes-update within neuron groups::
      stability[mu, j] = a*_l[mu, j] * <H_{l,j}, a_{l-1}[mu]>
      M^mu_l selects, per group, the neuron with the smallest *negative*
      stability among misclassified ones (the one easiest to flip).
      H_l <- H_l + 2 * sum_mu M^mu_l ⊙ ( a*_l^mu (a*_{l-1}^mu)^T )

* Reinforcement (Sec. 3.3): each weight gets a small probability of
  drifting further from zero, ``h <- h + 2 sign(h)`` w.p.
  ``p_r * sqrt(2 / (pi K_{l-1}))``.

The whole forward + backward + update loop uses ``brute.bit1`` matmuls for
every dot product: the only floating-point arithmetic is the integer-weight
accumulator (held in ``int32`` for headroom, clipped to ``int16``-range
afterwards).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from math import sqrt, pi
from typing import Optional, Sequence

import torch

import brute


# ── Tiny utilities (bit1 ↔ ±1) ────────────────────────────────────────────────

def _pm1_to_bit1(t: torch.Tensor) -> brute.Tensor:
    """Encode a ±1 tensor (any non-bool dtype is fine) as a packed bit1 tensor.

    Convention everywhere in this module: ``+1 ↦ True (1)``, ``-1 ↦ False (0)``.
    """
    if t.dtype == torch.bool:
        return brute.as_tensor(t, dtype=brute.bit1)
    return brute.as_tensor(t > 0, dtype=brute.bit1)


def _bit1_matmul_pm1(a_bit: brute.Tensor, w_bit: brute.Tensor) -> torch.Tensor:
    """A(B, K) @ W^T where both are bit1; returns int32 (B, N) ±1 dot product."""
    return a_bit @ w_bit


# ── Configuration ────────────────────────────────────────────────────────────

@dataclass
class BEPConfig:
    """Hyperparameters for BEP training (paper Sec. 4)."""

    # Trigger margin in Eq. 1 — update if (correct_logit - max_other) < r * K_L.
    r: float = 0.5
    # Backward gating threshold (Eq. 5) — neuron i is included iff |z_i| <= nu * K_{l-1}.
    nu: float = 0.05
    # Initial group size gamma_{0,l}. Each "winner" group elects ONE perceptron
    # per triggered sample. ``group_size_init`` must divide every hidden layer.
    group_size_init: int = 4
    # Reinforcement probability (CP+R). Rescaled per layer by sqrt(2/(pi K_{l-1})).
    p_reinforce: float = 0.5
    # Range for the integer hidden weights H_l. The paper uses B=16 ⇒ [-32768, 32767];
    # we keep a smaller, faster range by default that still trains stably.
    weight_clip: int = 2048
    # Initial std for the integer weights (drawn from a Gaussian, rounded).
    h_init_std: float = 4.0
    # If True, broadcast the reinforcement step (paper Sec. 3.3).
    use_reinforcement: bool = True


# ── BEP MLP ──────────────────────────────────────────────────────────────────

@dataclass
class BEPState:
    """Per-layer intermediates cached during the forward pass."""

    # ±1 activation as int8 (B, K_l). a_in[0] = a_0, a_in[L] = a_{L-1}, a_out[L] = a_L.
    a: list[torch.Tensor] = field(default_factory=list)
    # int32 pre-activation z_l = W_l a_{l-1} of shape (B, K_l). Index 0 is layer 1.
    z: list[torch.Tensor] = field(default_factory=list)
    # Packed bit1 activations (a_l) so the backward pass can do bit1 matmul.
    a_bit: list[brute.Tensor] = field(default_factory=list)
    # int32 final logits y_hat = P a_L of shape (B, C).
    logits: Optional[torch.Tensor] = None


class BEPModel:
    """Fully binary MLP trained with Binary Error Propagation.

    Parameters
    ----------
    layer_sizes : sequence of int
        ``[K_0, K_1, ..., K_L]``. ``K_0`` is the input dim (after binarisation),
        ``K_L`` is the size of the last hidden layer that feeds the BEF.
    classifier : torch.Tensor
        ±1 prototype matrix ``P`` of shape ``(n_classes, K_L)``. Generated by
        :func:`bef.generate_bef`. Stored both as float ±1 and as packed bit1.
    config : BEPConfig
    device : torch.device
    """

    def __init__(
        self,
        layer_sizes: Sequence[int],
        classifier: torch.Tensor,
        *,
        config: Optional[BEPConfig] = None,
        device: Optional[torch.device] = None,
        seed: Optional[int] = 0,
    ):
        self.config = config or BEPConfig()
        self.device = torch.device(device) if device is not None else torch.device("cpu")
        self.layer_sizes = list(layer_sizes)
        self.L = len(self.layer_sizes) - 1  # number of trainable binary layers

        assert classifier.dim() == 2, "classifier P must be 2-D"
        assert classifier.shape[1] == self.layer_sizes[-1], (
            f"classifier dim {classifier.shape[1]} != K_L {self.layer_sizes[-1]}"
        )
        self.n_classes = int(classifier.shape[0])
        self.K_L = int(classifier.shape[1])
        self._P_pm1 = classifier.to(self.device).float()
        self._P_bit = _pm1_to_bit1(self._P_pm1)

        # Group size: ``group_size_init`` must divide every layer width.
        for K in self.layer_sizes[1:]:
            if K % self.config.group_size_init != 0:
                raise ValueError(
                    f"group_size_init={self.config.group_size_init} must divide "
                    f"every layer size; got K={K}"
                )

        # Initialise integer hidden weights.
        gen = torch.Generator(device="cpu")
        if seed is not None:
            gen.manual_seed(int(seed))
        self.H: list[torch.Tensor] = []
        for l in range(self.L):
            K_out, K_in = self.layer_sizes[l + 1], self.layer_sizes[l]
            h = (torch.randn(K_out, K_in, generator=gen) * self.config.h_init_std).round().to(torch.int32)
            self.H.append(h.to(self.device))

        # Cached packed visible weights W_l and W_l^T (refreshed lazily).
        self._W_bit: list[Optional[brute.Tensor]] = [None] * self.L
        self._WT_bit: list[Optional[brute.Tensor]] = [None] * self.L
        self._cache_versions: list[int] = [-1] * self.L

    # ── Visible-weight cache ────────────────────────────────────────────────

    def _refresh_layer(self, l: int) -> None:
        """Re-pack ``W_l = sign(H_l)`` into bit1 if the integer weights changed."""
        ver = self.H[l]._version
        if self._cache_versions[l] == ver:
            return
        sign_w = self.H[l] >= 0  # ties (==0) ↦ +1 to match torch.sign convention being adapted
        # paper uses sign(H) with sign(0)=+1 effectively (since W lives in {±1})
        self._W_bit[l] = brute.as_tensor(sign_w, dtype=brute.bit1)
        self._WT_bit[l] = brute.as_tensor(sign_w.t().contiguous(), dtype=brute.bit1)
        self._cache_versions[l] = ver

    def visible_weight(self, l: int) -> brute.Tensor:
        self._refresh_layer(l)
        return self._W_bit[l]

    def visible_weight_T(self, l: int) -> brute.Tensor:
        self._refresh_layer(l)
        return self._WT_bit[l]

    # ── Forward pass (Sec. 3.1) ─────────────────────────────────────────────

    def forward(self, x_pm1: torch.Tensor) -> BEPState:
        """Run the binary forward pass on a batch of ±1 inputs.

        Parameters
        ----------
        x_pm1 : torch.Tensor
            Batch ``(B, K_0)`` of ±1 values (int8/float/bool — anything `> 0`).

        Returns
        -------
        BEPState
        """
        x_pm1 = x_pm1.to(self.device)
        state = BEPState()

        a_bit = _pm1_to_bit1(x_pm1)
        state.a_bit.append(a_bit)
        state.a.append(a_bit.unpack_pm1().to(torch.int8))

        for l in range(self.L):
            W_bit = self.visible_weight(l)             # (K_l, K_{l-1}) bit1
            z = _bit1_matmul_pm1(a_bit, W_bit)         # int32 (B, K_l)
            state.z.append(z)
            a_bit = _pm1_to_bit1(z > 0)                # propagate ±1 sign
            state.a_bit.append(a_bit)
            state.a.append(a_bit.unpack_pm1().to(torch.int8))

        # Logits y_hat = P a_L (still int32, ±1 dot product domain).
        state.logits = _bit1_matmul_pm1(state.a_bit[-1], self._P_bit)
        return state

    # ── Backward + update (Sec. 3.2 / 3.3) ──────────────────────────────────

    def step(self, state: BEPState, y: torch.Tensor) -> dict:
        """One BEP weight-update step (Eq. 7 + Eq. 9).

        Parameters
        ----------
        state : BEPState
            The state returned by :meth:`forward`.
        y : torch.Tensor
            Class labels ``(B,)`` (int64).

        Returns
        -------
        dict
            Diagnostic info (number of triggered samples, accuracy, etc.).
        """
        y = y.to(self.device).long()
        logits = state.logits                          # (B, C) int32
        B = logits.shape[0]
        C = self.n_classes

        # ── (1) Triggering rule (Eq. 1) ─────────────────────────────────────
        correct_logit = logits.gather(1, y.unsqueeze(1)).squeeze(1).to(torch.float32)
        # max_{c' ≠ c} y_hat[c']
        masked = logits.clone().to(torch.float32)
        masked.scatter_(1, y.unsqueeze(1), float("-inf"))
        max_other = masked.max(dim=1).values
        margin = correct_logit - max_other
        trigger = margin < self.config.r * self.K_L     # (B,) bool

        pred = logits.argmax(dim=1)
        n_correct = int((pred == y).sum().item())
        n_trig = int(trigger.sum().item())

        if n_trig == 0:
            return {
                "n_triggered": 0,
                "n_correct": n_correct,
                "batch_size": B,
                "acc": n_correct / max(B, 1),
            }

        # Sub-select triggered samples — every step below operates on them only.
        idx = trigger.nonzero(as_tuple=False).squeeze(1)
        y_trig = y[idx]

        # ── (2) Desired activations (Eq. 7) ─────────────────────────────────
        # a*_L = rho^{c}.
        a_star_pm1 = self._P_pm1[y_trig]                # (B', K_L) float ±1
        a_star_bit = _pm1_to_bit1(a_star_pm1)

        # Cache desired activations per layer for the weight update later.
        # a_star_list[l] = a*_l of shape (B', K_l); index 0 is layer 1's input target
        # (which is just the input a_0 — never updated), index l in [1..L] is a*_l.
        a_star_list: list[torch.Tensor] = [None] * (self.L + 1)
        a_star_list[self.L] = a_star_pm1

        for l in range(self.L - 1, 0, -1):
            # Gate at layer l+1: g_{l+1,i} = 1 iff |z_{l+1,i}| <= nu * K_l.
            z_next = state.z[l][idx]                     # (B', K_{l+1}) int32
            K_in_l = self.layer_sizes[l]                 # paper's K_l
            gate = z_next.abs() <= int(self.config.nu * K_in_l)

            # Compute W_{l+1}^T (g_{l+1} ⊙ a*_{l+1}). Because both operands are
            # ±1-valued (a* is ±1, gate zeros entries), we can NOT simply use a
            # bit1 matmul: the zero entries from gating break the ±1 invariant.
            #
            # Instead, observe that with a*_{l+1} ∈ {±1} and gate ∈ {0,1}::
            #     gated ∈ {-1, 0, +1}
            # And W_{l+1}^T @ gated yields an integer that has the *same sign*
            # as ``sum_i [gate_i = 1] W_{l+1, i, j} a*_{l+1, i}``. We can
            # compute this efficiently as the difference of two bit1 popcounts:
            #     (a*_{l+1} ⊙ gate) decomposed into (a_pos - a_neg) where
            #         a_pos = (a*_{l+1} == +1) & gate
            #         a_neg = (a*_{l+1} == -1) & gate
            # Then W_{l+1}^T @ a_pos - W_{l+1}^T @ a_neg, computed via
            # ``popcount(W^T & a_pos) - popcount(W^T & a_neg)`` for each output
            # neuron j. We approximate this by promoting gate*a* to ±1 with a
            # neutral zero-handling: any gated-out entry contributes +1*0 = 0,
            # which we encode as +1 in the bit1 view but cancel by subtracting
            # the same contribution from W_{l+1}^T @ all_ones_gate_complement.
            #
            # The cleaner equivalent (used here) is to do the matmul in int32
            # on the unpacked ±1 weights — for the small batch of TRIGGERED
            # samples this is cheap, while preserving exact paper semantics.
            W_next_pm1 = (self.H[l] >= 0).to(torch.int8) * 2 - 1   # (K_{l+1}, K_l)
            gated_a_star = (a_star_list[l + 1].to(torch.int8) * gate.to(torch.int8))  # (B', K_{l+1})
            pre = gated_a_star.to(torch.int32) @ W_next_pm1.to(torch.int32)            # (B', K_l)
            a_star_list[l] = (pre > 0).to(torch.float32) * 2 - 1                       # ±1
        # a_star_list[0] is the unchanged input (no target backprop into it).

        # ── (3) Aggregate weight update (Eq. 9) ─────────────────────────────
        for l in range(1, self.L + 1):
            # Pre-update stability per (sample, output_neuron):
            #     s[mu, j] = a*_l[mu, j] * <H_{l,j}, a_{l-1}[mu]>
            a_prev = state.a[l - 1][idx].to(torch.int32)            # (B', K_{l-1})
            z_curr = a_prev @ self.H[l - 1].t()                      # (B', K_l) int32
            a_star_l = a_star_list[l].to(torch.int32)               # (B', K_l) ±1
            stability = a_star_l * z_curr                            # (B', K_l)

            # Winner-takes-update within each group of size γ.
            K_out = self.layer_sizes[l]
            group_size = self.config.group_size_init
            n_groups = K_out // group_size
            stab_r = stability.view(-1, n_groups, group_size)
            negatives = stab_r < 0
            # Among the negatives, pick the one with the *smallest absolute*
            # stability (closest to flipping). Encode "not negative" as +inf so
            # it can never win the min-argmin.
            score = torch.where(negatives, stab_r.abs(), torch.full_like(stab_r, 2**30))
            local_argmin = score.argmin(dim=2)                       # (B', n_groups)
            any_neg = negatives.any(dim=2)                           # (B', n_groups)

            # Build the (B', K_l) ±1 mask: ones exactly at chosen neurons.
            mask = torch.zeros(stability.shape, dtype=torch.int32, device=self.device)
            b_idx = torch.arange(stability.shape[0], device=self.device).unsqueeze(1).expand(-1, n_groups)
            g_offset = torch.arange(n_groups, device=self.device) * group_size
            flat_neuron = g_offset.unsqueeze(0) + local_argmin       # (B', n_groups)
            mask[b_idx[any_neg], flat_neuron[any_neg]] = 1

            # Per-sample candidate update is a*_l (a_{l-1})^T ∈ {±1} — same
            # form as the CP/CP+R rule the paper reduces to in the single-
            # neuron case (Sec. 3.3 footnote: "adds [...] to the input vector
            # a_{l-1}^μ whenever the desired output a*_l^μ is +1"). Using the
            # *visible* incoming activation also matches the BNN-main reference
            # implementation. The aggregated update across triggered samples:
            #     delta_H[j, k] = 2 * sum_mu mask[mu, j] * a*_l[mu, j] * a_{l-1}[mu, k]
            # which equals  2 * ( (a*_l ⊙ mask)^T @ a_{l-1} ).
            masked_a_star = a_star_l * mask                          # (B', K_l)
            delta = masked_a_star.t() @ a_prev                       # (K_l, K_{l-1}) int32
            self.H[l - 1] += 2 * delta

            # ── Reinforcement step (Sec. 3.3) ────────────────────────────────
            if self.config.use_reinforcement and self.config.p_reinforce > 0:
                K_in = self.layer_sizes[l - 1]
                p = self.config.p_reinforce * sqrt(2.0 / (pi * max(K_in, 1)))
                # Probability is capped to keep things sane.
                p = min(max(p, 0.0), 1.0)
                if p > 0:
                    rein_mask = (torch.rand(self.H[l - 1].shape, device=self.device) < p)
                    sign_h = torch.where(
                        self.H[l - 1] > 0, torch.tensor(1, device=self.device, dtype=torch.int32),
                        torch.where(
                            self.H[l - 1] < 0, torch.tensor(-1, device=self.device, dtype=torch.int32),
                            torch.tensor(0, device=self.device, dtype=torch.int32),
                        ),
                    )
                    self.H[l - 1] += 2 * sign_h * rein_mask.to(torch.int32)

            # Clip to the B-bit integer range.
            clip = int(self.config.weight_clip)
            self.H[l - 1].clamp_(-clip, clip)

        return {
            "n_triggered": n_trig,
            "n_correct": n_correct,
            "batch_size": B,
            "acc": n_correct / max(B, 1),
        }

    # ── Inference helper ────────────────────────────────────────────────────

    @torch.no_grad()
    def predict(self, x_pm1: torch.Tensor, *, batch_size: int = 1024) -> torch.Tensor:
        """Predicted class indices for a batch of ±1 inputs."""
        preds = []
        for i in range(0, x_pm1.shape[0], batch_size):
            xb = x_pm1[i : i + batch_size]
            state = self.forward(xb)
            preds.append(state.logits.argmax(dim=1))
        return torch.cat(preds, dim=0)

    @torch.no_grad()
    def accuracy(self, x_pm1: torch.Tensor, y: torch.Tensor, *, batch_size: int = 1024) -> float:
        pred = self.predict(x_pm1.to(self.device), batch_size=batch_size).cpu()
        return float((pred == y.cpu().long()).float().mean().item())

    # ── Diagnostics ─────────────────────────────────────────────────────────

    def num_parameters(self) -> int:
        return sum(int(h.numel()) for h in self.H)

    def __repr__(self) -> str:
        sizes = " → ".join(str(k) for k in self.layer_sizes)
        return f"BEPModel({sizes}, classes={self.n_classes}, params={self.num_parameters():,})"
