# EmbedBinary.cmake — read a binary file and emit a C header with its bytes.
#
# Variables required:
#   IN   path to the input binary (e.g. .metallib)
#   OUT  path to the output .h
#   SYM  symbol name for the embedded array
#
# Resulting header defines:
#   static const unsigned char  ${SYM}[]  = { 0x.., 0x.., ... };
#   static const unsigned long  ${SYM}_len = N;

file(READ "${IN}" HEX_DATA HEX)

string(LENGTH "${HEX_DATA}" HEX_LEN)
math(EXPR BYTE_LEN "${HEX_LEN} / 2")

set(BODY "")
set(COL 0)
math(EXPR LAST "${HEX_LEN} - 2")
foreach(I RANGE 0 ${LAST} 2)
    string(SUBSTRING "${HEX_DATA}" ${I} 2 BYTE)
    string(APPEND BODY "0x${BYTE},")
    math(EXPR COL "${COL} + 1")
    if(COL EQUAL 16)
        string(APPEND BODY "\n    ")
        set(COL 0)
    endif()
endforeach()

file(WRITE "${OUT}"
"// AUTO-GENERATED by cmake/EmbedBinary.cmake — do not edit.
// Source: ${IN}
#pragma once
#include <stddef.h>

static const unsigned char ${SYM}[] = {
    ${BODY}
};
static const unsigned long ${SYM}_len = ${BYTE_LEN}UL;
")
